name             'sightglass'
maintainer       'Joshua Ma'
maintainer_email 'josh@benchling.com'
license          'all_rights'
description      'Installs/Configures sightglass'
long_description 'Installs/Configures sightglass'
version          '0.1.0'

depends 'java', '~> 1.31.0'
depends 'nginx', '~> 2.7.4'
depends 'elasticsearch', '~> 0.3.13'
