name             'sightglass2'
maintainer       'Raymond Lu'
maintainer_email 'raylu@benchling.com'
license          'all_rights'
description      'Installs/configures sightglass2'
long_description 'Installs/configures sightglass2'
version          '0.1.0'

depends 'java', '~> 2.2.1'
depends 'elasticsearch', '~> 2.5.0'
depends 'sysctl', '~> 1.0.5'
